### ISSUE TITLE
Platforms listed multiple times - Previously not displayed at all. 

### ISSUE THREAD

**Issue by OfficialGMYT** [OfficialGMYT/IGDB-Widget#2]
Currently, the Platforms don't display properly, therefore, the user can't actually read what platforms the title will be released on. 

![capture](https://cloud.githubusercontent.com/assets/13305475/19366408/fa1bace4-918e-11e6-9807-e65096168e64.PNG)

**Comment by edstub207** [comment]
This issue is partially fixed. Now that the API Is pulling down the platforms the platforms are actually displayed. However, the platforms are displayed multiple times. This should be a quick fix.

**Comment by OfficialGMYT** [comment]
Marked as fixed as this issue has been fully fixed in version V3 (IGDB-Modern-Widget)
