### ISSUE TITLE
Date Chart Image is duplicated

### ISSUE THREAD

**Issue by OfficialGMYT** [OfficialGMYT/IGDB-Widget#4]
Currently, the date chart image is displayed twice 

![capture](https://cloud.githubusercontent.com/assets/13305475/19366568/91f4ea80-918f-11e6-987a-9bbff1383a2a.PNG)

**Comment by edstub207** [comment]
This feature has been removed from the plugin while the issue is being fixed.

**Comment by OfficialGMYT** [comment]
Marked as fixed as this issue has been fully fixed in version V3 (IGDB-Modern-Widget)
