### ISSUE TITLE
Current Month of releases function not working as intended

### ISSUE THREAD

**Issue by OfficialGMYT** [OfficialGMYT/IGDB-Widget#5]
Currently, the plugin when the Current Month function is activated only displays three releases and isn't linked to the "Limit result" option.

Also, these releases don't show the upcoming releases for the current month but the first three releases of games in that month. Therefore the function needs to be re-coded and fixed. 

![capture](https://cloud.githubusercontent.com/assets/13305475/19366795/5848640a-9190-11e6-95ae-b1ccc8ca2c53.PNG)

**Comment by edstub207** [comment]
As a temp fix the hard coded date has been changed to the 1st September 2018 so the date field doesn't get displayed. Also changed option from current_month to current_day. Ideal situation would be to set up a current_week option.

**Comment by OfficialGMYT** [comment]
Marked as fixed as this issue has been fully fixed in version V3 (IGDB-Modern-Widget)
